# Generated by Django 4.2.28 on 2026-02-13 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("date_assigned", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="assignments/"),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_graded", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUB", "Published"),
                            ("CANC", "Cancelled"),
                            ("COMP", "Completed"),
                        ],
                        default="PUB",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="classes.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACAD", "Academic"),
                            ("SPORT", "Sports"),
                            ("CULT", "Cultural"),
                            ("HOL", "Holiday"),
                            ("MEET", "Meeting"),
                            ("EXAM", "Examination"),
                            ("OTHER", "Other"),
                        ],
                        default="ACAD",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/banners/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORM", "Normal"),
                            ("HIGH", "High"),
                            ("CRIT", "Critical"),
                        ],
                        default="NORM",
                        max_length=10,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("target_roles", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requires_rsvp", models.BooleanField(default=False)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(blank=True, to="classes.class"),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("ACAD", "Academic"),
                            ("ADMIN", "Administrative"),
                            ("EMER", "Emergency"),
                            ("HOL", "Holiday"),
                        ],
                        default="GEN",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORM", "Normal"),
                            ("HIGH", "High"),
                            ("URG", "Urgent"),
                        ],
                        default="NORM",
                        max_length=10,
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="notices/"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="notices/images/"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("target_roles", models.JSONField(blank=True, default=list)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(blank=True, to="classes.class"),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="ClassMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="class_messages/"
                    ),
                ),
                ("send_to_students", models.BooleanField(default=True)),
                ("send_to_parents", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="classes.class",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_class_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "New Assignment"),
                            ("SCORE", "Score Posted"),
                            ("ATTEND", "Attendance"),
                            ("EVENT", "Event"),
                            ("PAY", "Payment"),
                            ("GEN", "General"),
                            ("ALERT", "Alert"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="announcemen_recipie_5e73d9_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="announcemen_created_d6a384_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NoticeRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="announcements.notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("notice", "user")},
            },
        ),
        migrations.CreateModel(
            name="EventRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GOING", "Going"),
                            ("MAYBE", "Maybe"),
                            ("NOT_GOING", "Not Going"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="announcements.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("submission_text", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUB", "Submitted"),
                            ("LATE", "Late"),
                            ("GRAD", "Graded"),
                            ("RET", "Returned"),
                        ],
                        default="SUB",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="announcements.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
