# Generated by Django 4.2.28 on 2026-02-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slogan", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school/logo/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="school/"),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("opening_time", models.TimeField(default="08:00")),
                ("closing_time", models.TimeField(default="15:00")),
                (
                    "half_day_opening",
                    models.TimeField(blank=True, default="08:00", null=True),
                ),
                (
                    "half_day_closing",
                    models.TimeField(blank=True, default="12:00", null=True),
                ),
                (
                    "current_term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        default="FIRST",
                        max_length=10,
                    ),
                ),
                (
                    "current_academic_year",
                    models.CharField(default="2024/2025", max_length=9),
                ),
                ("next_term_begins", models.DateField(blank=True, null=True)),
                ("primary_color", models.CharField(default="#ff69b4", max_length=7)),
                ("secondary_color", models.CharField(default="#ffb6c1", max_length=7)),
                ("accent_color", models.CharField(default="#ffffff", max_length=7)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Profile",
                "verbose_name_plural": "School Profile",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="school.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "unique_together": {("academic_year", "term")},
            },
        ),
    ]
