# Generated by Django 4.2.28 on 2026-02-13 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=50, unique=True)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("NCE", "NCE"),
                            ("BED", "Bachelor's in Education"),
                            ("BA", "Bachelor's Degree"),
                            ("MSC", "Master's Degree"),
                            ("PHD", "PhD"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("specialization", models.CharField(max_length=200)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Time"),
                            ("PART", "Part Time"),
                            ("CONT", "Contract"),
                            ("VISIT", "Visiting"),
                        ],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                ("date_employed", models.DateField()),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="teachers/cv/"),
                ),
                (
                    "certificates",
                    models.FileField(
                        blank=True, null=True, upload_to="teachers/certificates/"
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("pension_number", models.CharField(blank=True, max_length=50)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("is_class_teacher", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("year_obtained", models.PositiveIntegerField()),
                ("grade", models.CharField(blank=True, max_length=50)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teacher Subject Expertise",
                "unique_together": {("teacher", "subject")},
            },
        ),
    ]
