# Generated by Django 4.2.28 on 2026-02-13 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=50, unique=True)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pending Review"),
                            ("REV", "Under Review"),
                            ("ACC", "Accepted"),
                            ("REJ", "Rejected"),
                            ("WAIT", "Waitlisted"),
                            ("ENR", "Enrolled"),
                        ],
                        default="PEND",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Nigeria", max_length=100),
                ),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("previous_class", models.CharField(blank=True, max_length=50)),
                ("father_name", models.CharField(blank=True, max_length=200)),
                ("father_phone", models.CharField(blank=True, max_length=15)),
                ("father_email", models.EmailField(blank=True, max_length=254)),
                ("mother_name", models.CharField(blank=True, max_length=200)),
                ("mother_phone", models.CharField(blank=True, max_length=15)),
                ("mother_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                ("guardian_phone", models.CharField(blank=True, max_length=15)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_relationship", models.CharField(blank=True, max_length=50)),
                (
                    "birth_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/birth_certificates/",
                    ),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="applications/photos/"
                    ),
                ),
                (
                    "previous_results",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/results/"
                    ),
                ),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("admission_number", models.CharField(blank=True, max_length=50)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                (
                    "applying_for_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="classes.classlevel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="EntranceExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField()),
                (
                    "english_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "mathematics_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "general_knowledge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_passed", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrance_exams",
                        to="admissions.application",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="admissions.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
